//for testing will use API for data source later

export const foodData = [
  {
    id: 0,
    title: 'Ramen Burger',
    poster: 'https://c8.alamy.com/comp/HGB7R0/new-fast-food-ramen-burger-close-up-on-a-paper-on-the-wooden-table-HGB7R0.jpg',
    price: '50.000 VNĐ',
    weight: '420g',
    type: 'burger',
  },
  {
    id: 1,
    title: 'Rustic Sandwich',
    poster: 'https://c8.alamy.com/comp/HFHJHT/rustic-sandwich-with-beefsteak-fried-egg-and-french-fries-vertical-HFHJHT.jpg',
    price: '40.000 VNĐ',
    weight: '420g',
    type: 'other',
  },
  {
    id: 2,
    title: 'Danish Hotdog',
    poster: 'https://c8.alamy.com/comp/HRFARD/danish-hot-dogs-close-up-on-the-table-vertical-HRFARD.jpg',
    price: '35.000 VNĐ',
    weight: '420g',
    type: 'other',
  },
  {
    id: 3,
    title: 'Sloppy Joe',
    poster: 'https://c8.alamy.com/comp/M03G1F/fast-food-sandwich-sloppy-joe-with-tomato-sauce-and-fries-close-up-M03G1F.jpg',
    price: '50.000 VNĐ',
    weight: '420g',
    type: 'burger',
  },
  {
    id: 4,
    title: 'Bánh mì',
    poster: 'https://www.bakersroyale.com/wp-content/uploads/2018/04/Banh-Mi-_-Bakers-Royale-630x945.jpg',
    price: '20.000 VNĐ',
    weight: '420g',
    type: 'other',
  },
  {
    id: 5,
    title: 'Corn dog',
    poster: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsbBa8NJs__DbUXjqeCN8Cg28e_7ecuBtUg3m9w-JnjHtU_2lx',
    price: '25.000 VNĐ',
    weight: '420g',
    type: 'other',
  },
  {
    id: 6,
    title: 'Fries',
    poster: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4Nhqd9cg_4WZn9CveB5cqL7q1jBx4MXEcj8MIkJSrVC_DvGZs',
    price: '15.000 VNĐ',
    weight: '420g',
    type: 'other',
  },
  {
    id: 7,
    title: 'Salmon Burger',
    poster: 'https://nourishedkitchen.com/wp-content/uploads/2016/08/salmon-burger-vertical-1-of-1.jpg',
    price: '65.000 VNĐ',
    weight: '420g',
    type: 'burger',
  },
  {
    id: 8,
    title: 'Tropical Burger',
    poster: 'http://www.nibblesandfeasts.com/wp-content/uploads/2016/07/02-13536-post/tropical-burger-Hero-2-vertical-2.jpg',
    price: '55.000 VNĐ',
    weight: '420g',
    type: 'burger',
  },
  {
    id: 9,
    title: 'Lamb Burger',
    poster: 'https://saltpepperskillet.com/wp-content/uploads/lamb-burgers-1.jpg',
    price: '45.000 VNĐ',
    weight: '420g',
    type: 'burger',
  },
  {
    id: 10,
    title: 'Bacon Burger',
    poster: 'http://www.lifeasastrawberry.com/wp-content/uploads/2016/05/simple-salmon-burger-recipe.jpg',
    price: '45.000 VNĐ',
    weight: '420g',
    type: 'burger',
  },
  {
    id: 11,
    title: 'Brome Burger',
    poster: 'http://www.epicureantravelerblog.com/wp-content/uploads/2017/01/BromeBurgerVertical.jpg',
    price: '35.000 VNĐ',
    weight: '420g',
    type: 'burger',
  },
  {
    id: 12,
    title: 'Onion Burger',
    poster: 'https://wallpapershome.com/images/pages/pic_v/630.jpg',
    price: '35.000 VNĐ',
    weight: '420g',
    type: 'burger',
  },
  {
    id: 13,
    title: 'Guacamole Burger',
    poster: 'https://www.thedailymeal.com/sites/default/files/u3900/4_burger_nomfood.jpg',
    price: '40.000 VNĐ',
    weight: '420g',
    type: 'burger',
  },
  {
    id: 14,
    title: 'Chipotle Burger',
    poster: 'https://www.thedailymeal.com/sites/default/files/u3900/1_burger_verticalfood.jpg',
    price: '45.000 VNĐ',
    weight: '420g',
    type: 'burger',
  },
  {
    id: 15,
    title: 'Turkey Burger',
    poster: 'https://bloximages.chicago2.vip.townnews.com/winonadailynews.com/content/tncms/assets/v3/editorial/c/62/c62668a4-4d4f-58ce-89df-fcd689cdb70e/5581ce4087df1.image.jpg',
    price: '50.000 VNĐ',
    weight: '420g',
    type: 'burger',
  },
  {
    id: 16,
    title: 'Tuna Pizza',
    poster: 'https://c8.alamy.com/comp/HA12G1/italian-pizza-with-tuna-olives-and-arugula-close-up-on-the-table-vertical-HA12G1.jpg',
    price: '30.000 VNĐ',
    weight: '420g',
    type: 'pizza',
  },
  {
    id: 17,
    title: 'Shrimp Pizza',
    poster: 'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX20836598.jpg',
    price: '35.000 VNĐ',
    weight: '420g',
    type: 'pizza',
  },
  {
    id: 18,
    title: 'Turkey Burger',
    poster: 'https://bloximages.chicago2.vip.townnews.com/winonadailynews.com/content/tncms/assets/v3/editorial/c/62/c62668a4-4d4f-58ce-89df-fcd689cdb70e/5581ce4087df1.image.jpg',
    price: '50.000 VNĐ',
    weight: '420g',
    type: 'burger',
  },
  {
    id: 19,
    title: 'Eggplant Pizza',
    poster: 'https://previews.123rf.com/images/lenyvavsha/lenyvavsha1608/lenyvavsha160800480/62706669-pizza-with-eggplant-salami-and-mozzarella-close-up-on-a-wooden-board-vertical-view-from-above.jpg',
    price: '40.000 VNĐ',
    weight: '420g',
    type: 'pizza',
  },
  {
    id: 20,
    title: 'Vegan Pizza',
    poster: 'https://createmindfully.com/wp-content/uploads/2017/06/vegan-hawaiian-bbq-pizza-vertical-four.jpg',
    price: '30.000 VNĐ',
    weight: '420g',
    type: 'pizza',
  },
  {
    id: 21,
    title: 'Cheese Pizza',
    poster: 'https://www.the-girl-who-ate-everything.com/wp-content/uploads/2014/10/TheGirlWhoAteEverything_BaconCheeseburgerPizza_Vertical41.jpg',
    price: '50.000 VNĐ',
    weight: '420g',
    type: 'pizza',
  },
  {
    id: 22,
    title: 'Hawaiian Pizza',
    poster: 'https://peasandcrayons.com/wp-content/uploads/2016/06/BBQ-barbecue-hawiian-pizza-flatbreads-recipe-PEASandCRAYONS-6468.jpg',
    price: '30.000 VNĐ',
    weight: '420g',
    type: 'pizza',
  },
  {
    id: 23,
    title: 'Normal Pizza',
    poster: 'http://7ingredientsorless.com/wp-content/uploads/2016/08/2-Ingredient-Pizza-dough.jpg',
    price: '30.000 VNĐ',
    weight: '420g',
    type: 'pizza',
  },
  {
    id: 24,
    title: 'Pepper Pizza',
    poster: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQv-3YFsT6NJkt5mGHI9GIscSZTMnjtSKH3s1PdkP-BVhc_gmkk',
    price: '30.000 VNĐ',
    weight: '420g',
    type: 'pizza',
  },
  {
    id: 25,
    title: 'Neapolitan Pizza',
    poster: 'https://st.depositphotos.com/1373322/4178/i/950/depositphotos_41780493-stock-photo-neapolitan-pizza-margarita-closeup-vertical.jpg',
    price: '45.000 VNĐ',
    weight: '420g',
    type: 'pizza',
  },
  {
    id: 26,
    title: 'Coca Cola (Bottle)',
    poster: 'http://24.media.tumblr.com/tumblr_mdc82tvBnU1rcjq6vo1_500.png',
    price: '15.000 VNĐ',
    weight: '420ml',
    type: 'drink',
  },
  {
    id: 27,
    title: 'Coca Cola (Can)',
    poster: 'https://d2wvksc3i53c0p.cloudfront.net/media/catalog/product/optimized/2/0/203f96f71d36fc598c5c12ebc3bb2318/p96120b.jpg',
    price: '15.000 VNĐ',
    weight: '420ml',
    type: 'drink',
  },
  {
    id: 28,
    title: 'Diet Coke',
    poster: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/401057178-ph-osm-dko-330-can-tickpink-gb-r1-1536326433.png?crop=1xw:1xh;center,top&resize=480:*',
    price: '13.000 VNĐ',
    weight: '420ml',
    type: 'drink',
  },
  {
    id: 29,
    title: 'Pepsi (Can)',
    poster: 'https://www.melcomonline.com/pub/media/catalog/product/cache/image/620x678/e9c3970ab036de70892d86c6d221abfe/4/0/40094a.jpg',
    price: '15.000 VNĐ',
    weight: '420ml',
    type: 'drink',
  },
  {
    id: 30,
    title: 'Cocacola Zero',
    poster: 'https://cdn.officestationery.co.uk/products/113844-500/Coca-Cola-Coke-Zero-330ml-Soft-Drink-Can-Pack-of-2.jpg',
    price: '15.000 VNĐ',
    weight: '420ml',
    type: 'drink',
  },
];
